language: objective-c
osx_image: xcode10.1
xcode_workspace: nWorkout.xcworkspace
xcode_scheme: nWorkout
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

env:
 global:
   - TRAVIS=TRAVIS
 matrix:
   - DESTINATION="platform=iOS Simulator,OS=10.2,id=63A0BA5F-3911-496F-BF2E-512830B4AD7F"
