name: nWorkout
options:
  bundleIdPrefix: io.lanza
targets:
  nWorkout:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [Source]
    settings:
      configs:
        debug:
          CUSTOM_BUILD_SETTING: my_debug_value

