# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

update_fastlane
fastlane_version "2.9.0"
default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  lane :blah do
    cert
    sigh(force: true)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "nWorkout") # Build your app - more options available
    pilot
    testflight

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Just tf"
  lane :tf do
    testflight
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
     snapshot
    gym(scheme: "nWorkout") # Build your app - more options available
    deliver(force: true)
    frameit
  end

  desc "Take Screenshots"
  lane :screenshot do
    snapshot
  end

  after_all do |lane|
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end
